<!--<h1>Hello World</h1>
<p id='first'></p>
<h1><?php //echo $this->escapeHtml($this->getMessage()); ?></h1>
<div class="col-md-6">
   <p>Блок1</p>
</div>
<div class="col-md-6">
   <p>Блок2</p>
</div>
-->
<div class="col-md-6">
    <form id="form1" role="form" method="post" action="">
  <div class="form-group">
    <label for="mail">Введіть ваш емейл</label>
    <input type="email" name="mail" class="form-control" id="mail" placeholder="емейл">
  </div>
  <div class="form-group">
    <label for="phone">Введіть ваш телефон</label>
    <input type="text" name="phone" maxlength="12" minlength="10" class="form-control" id="phone" placeholder="телефон">
  </div>
  
  <div class="form-group">
    <label for="message">Введіть текст повідомлення</label>
	<textarea id="message" name="message" class="form-control" placeholder="текст повідомлення" rows="3"></textarea>
  </div>
 
  <button type="submit" class="btn btn-info">Відправити дані</button>
</form>
<p id='tt'><p>
</div>
<script>
 //alert("Привіт!");
  //require(['bootstrap']);
  require([ 'jquery'], function($){
    //$('#first').text('Записав текст у темплейті');
	$( '#form1' ).submit(function( event ) {
  event.preventDefault();
  
  var form = $( this );
 
  $.ajax({
    type: 'POST',
    url: '../save/save',
    data: form.serialize(),
    success: function( html ) {
      console.log( html );
	  $("#tt").empty();
      $("#tt").html(html);
	  $('#form1')[0].reset();
    }
  });
  return false;
});


});

  
</script>